### ISSUE TITLE
node listing considered harmful when in offline

### ISSUE THREAD

**Issue by matti** [kontena/kontena-cloud-issues#14]
![asdfasdf](https://user-images.githubusercontent.com/3893/32209871-30377180-be13-11e7-804c-4b9c355b288c.png)

**Comment by matti** [comment]
it's so easy to miss the status when CPU,MEM,DISK look like it's online

**Comment by nevalla** [comment]
Thanks for reporting. Now CPU, MEM, DISK values are not shown for offline nodes.
